-- Add JSONB column for extra Notion properties
ALTER TABLE contacts 
ADD COLUMN IF NOT EXISTS notion_properties JSONB DEFAULT '{}'::jsonb;

-- Create Sync Logs table
CREATE TABLE IF NOT EXISTS sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    status TEXT NOT NULL,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create index for faster querying of logs
CREATE INDEX IF NOT EXISTS idx_sync_logs_created_at ON sync_logs(created_at DESC);
