-- =============================================================================
-- Jarvis Sync Service - Database Schema
-- =============================================================================
-- Run this in your Supabase SQL Editor to set up all required tables.
-- This creates the core schema for contact and meeting synchronization.
-- =============================================================================

-- =============================================================================
-- CONTACTS TABLE
-- =============================================================================
-- Central store for all contacts, synced with Google Contacts and Notion CRM

CREATE TABLE IF NOT EXISTS contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Basic Info
    email TEXT,
    phone TEXT,
    first_name TEXT,
    last_name TEXT,
    company TEXT,
    job_title TEXT,
    location TEXT,
    notes TEXT,
    
    -- External IDs for sync
    google_resource_name TEXT UNIQUE,  -- Google People API resource name
    notion_page_id TEXT UNIQUE,        -- Notion page ID
    
    -- Sync timestamps
    notion_updated_at TIMESTAMP WITH TIME ZONE,  -- Last edit time in Notion
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,  -- Soft delete
    
    -- Extra Notion properties (JSONB for flexibility)
    notion_properties JSONB DEFAULT '{}'::jsonb
);

-- Indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(email);
CREATE INDEX IF NOT EXISTS idx_contacts_google_resource ON contacts(google_resource_name);
CREATE INDEX IF NOT EXISTS idx_contacts_notion_page ON contacts(notion_page_id);
CREATE INDEX IF NOT EXISTS idx_contacts_updated_at ON contacts(updated_at);
CREATE INDEX IF NOT EXISTS idx_contacts_deleted_at ON contacts(deleted_at) WHERE deleted_at IS NOT NULL;

-- =============================================================================
-- MEETINGS TABLE
-- =============================================================================
-- Stores meetings synced between Notion and Supabase

CREATE TABLE IF NOT EXISTS meetings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Meeting Info
    title TEXT NOT NULL,
    date DATE,
    summary TEXT,
    notes TEXT,
    
    -- Link to contact
    contact_id UUID REFERENCES contacts(id) ON DELETE SET NULL,
    
    -- External IDs for sync
    notion_page_id TEXT UNIQUE,
    
    -- Sync tracking
    notion_updated_at TIMESTAMP WITH TIME ZONE,
    last_sync_source TEXT,  -- 'notion' or 'supabase' - prevents ping-pong updates
    
    -- Timestamps
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE  -- Soft delete
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_meetings_date ON meetings(date);
CREATE INDEX IF NOT EXISTS idx_meetings_contact ON meetings(contact_id);
CREATE INDEX IF NOT EXISTS idx_meetings_notion_page ON meetings(notion_page_id);
CREATE INDEX IF NOT EXISTS idx_meetings_updated_at ON meetings(updated_at);
CREATE INDEX IF NOT EXISTS idx_meetings_last_sync_source ON meetings(last_sync_source);
CREATE INDEX IF NOT EXISTS idx_meetings_deleted_at ON meetings(deleted_at) WHERE deleted_at IS NOT NULL;

-- =============================================================================
-- SYNC LOGS TABLE
-- =============================================================================
-- Tracks all sync operations for debugging and monitoring

CREATE TABLE IF NOT EXISTS sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,      -- e.g., 'sync_start', 'create_google', 'update_notion'
    status TEXT NOT NULL,          -- e.g., 'info', 'success', 'error', 'warning'
    message TEXT,                  -- Human-readable description
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for querying recent logs
CREATE INDEX IF NOT EXISTS idx_sync_logs_created_at ON sync_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sync_logs_event_type ON sync_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_sync_logs_status ON sync_logs(status);

-- =============================================================================
-- OPTIONAL: TASKS TABLE (for future use)
-- =============================================================================
-- Placeholder for task sync functionality

CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    due_date DATE,
    completed BOOLEAN DEFAULT false,
    priority TEXT,
    
    -- Link to contact if task is related to someone
    contact_id UUID REFERENCES contacts(id) ON DELETE SET NULL,
    
    -- External IDs
    notion_page_id TEXT UNIQUE,
    todoist_id TEXT UNIQUE,
    
    -- Sync tracking
    notion_updated_at TIMESTAMP WITH TIME ZONE,
    last_sync_source TEXT,
    
    -- Timestamps
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_contact ON tasks(contact_id);
CREATE INDEX IF NOT EXISTS idx_tasks_notion_page ON tasks(notion_page_id);

-- =============================================================================
-- ENABLE ROW LEVEL SECURITY (Optional)
-- =============================================================================
-- Uncomment if you want to add RLS policies

-- ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE meetings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE sync_logs ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- TRIGGERS FOR updated_at
-- =============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to all tables
DROP TRIGGER IF EXISTS update_contacts_updated_at ON contacts;
CREATE TRIGGER update_contacts_updated_at
    BEFORE UPDATE ON contacts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_meetings_updated_at ON meetings;
CREATE TRIGGER update_meetings_updated_at
    BEFORE UPDATE ON meetings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_tasks_updated_at ON tasks;
CREATE TRIGGER update_tasks_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
